[package]
name = "lr-parsing-tools"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "main_benchmark"
harness = false